#!/bin/bash
set -e

case "$1" in
    remove|purge)
        # Remove nginx configuration
        rm -f /etc/nginx/hifiberry-vu-meter.nginx
        rm -f /etc/nginx/hifiberry-api.d/hifiberry-vu-meter.nginx

        # Reload nginx if running
        if nginx -t 2>/dev/null; then
            invoke-rc.d nginx reload >/dev/null 2>&1 || true
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        :
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installsystemduser/13.24.2
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'vu-meter.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
